services:
  postgres:
    image: postgres
    ports:
      - '6543:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  postgres:
